### ISSUE TITLE
Open up branch permissions for pull requests?

### ISSUE THREAD

**Issue by moogzy** [bgplab/bgplab#12]
Hey @ipspace,

Thanks for putting this repo together. I was testing out Codespaces and started running through some of the labs, along the way I fixed some typos/clarifications in the first two labs.

However I don't have permission to send you a pull request, via pushing a dev branch up. Would you be interested in opening those permissions up? 

`
❯ git commit -as
[update-documentation-labs-0-and-1 bd3a46c] Update lab documentation for basic/0-frr and basic/1-session labs
 2 files changed, 74 insertions(+), 34 deletions(-)
❯ git push
remote: Permission to bgplab/bgplab.git denied to moogzy.
fatal: unable to access 'https://github.com/bgplab/bgplab/': The requested URL returned error: 403
`

I sent you a fork to review instead.... just in case thats what you prefer --> https://github.com/bgplab/bgplab/pull/11

Cheers!

**Comment by ipspace** [comment]
Sending a PR through a fork is exactly the way to go ;) Thank you!
