### ISSUE TITLE
Alternate solution to make documentation links work in Codespaces

### ISSUE THREAD

**Issue by ipspace** [bgplab/bgplab#15]
I could move the Markdown files and images to the **docs** directory and have just a symbolic link named 'instructions.md' in the lab directory.

_Originally posted by @ipspace in https://github.com/bgplab/bgplab/issues/11#issuecomment-2189453495_

**Comment by ipspace** [comment]
Implemented in fff0ac67f9622d01cccda58e075b0bfd6930fa0a, documentation adjusted in b2c83516cbe2330a5b4f9ffc83c4f1f7acd11f3c

Thanks again @moogzy for pointing this out!

**Comment by moogzy** [comment]
Nice! Will give it a spin. Thanks.
