### ISSUE TITLE
BGP daemon is not started in FRR container in the initial lab exercises

### ISSUE THREAD

**Issue by ipspace** [bgplab/bgplab#4]
(transferred from https://github.com/ipspace/netlab/issues/1012)

The FRR daemons file does not start the BGP daemon on the customer router in the initial lab exercises (1-session and 2-multihomed) because their goal is to start BGP from scratch. However, it might not be possible to restart daemons in FRR container.

At the very minimum, we need an in-depth description of what to do on FRR or Cumulus Linux. A plugin that would tweak the daemons file would be even better.

**Comment by barajus** [comment]
Hi, based on my quick and dirty testing, it is indeed not possible to restart FRR in the container (reload is also not enough to activated bgpd).

```
rtr(bash)#/etc/init.d/frr restart
Stopping Frr monitor daemon:ubuntu@primary:~/bgplab/basic/1-session$ netlab connect rtr
Connecting to container clab-session-rtr, starting bash
Error response from daemon: Container 15591aa488782f05b3295940e692bc27d0ea9ea452daa3af6a75ebaeebaadfbf is not running
```

**Comment by ipspace** [comment]
Makes sense, as FRR container runs the top-level FRR process as the init process, and killing it kills the container. Will figure out a fix for FRR containers and document what needs to be done for FRR-in-a-VM or Cumulus Linux.

Thanks a million for figuring this one out!
