### ISSUE TITLE
Validation missing in some labs

### ISSUE THREAD

**Issue by barajus** [bgplab/bgplab#7]
Hi :)
As a comment I would suggest to provide a `netlab validate` for each lab.
Not a big deal, and actually some labs have a very nice step-by-step validation, but still it's quite pleasant and consistent when one user chain labs after labs.

**Comment by ipspace** [comment]
> As a comment I would suggest to provide a `netlab validate` for each lab.

Glad to hear that's at least one person out there appreciating the automated validation ;)

Adding validation to all labs is definitely the ultimate goal, but I have to put better infrastructure in place. the individual validation files (validate.yml) are ridiculously complex, and if I cut-and-paste them around, I'll create an enormous amount of technical debt.

What I'd like to have is some higher-level commands like "validate BGP session between here and there" or "validate there are some BGP routes in the BGP table" or "validate BGP neighbor X sent us some routes" or "validate there are two paths to this prefix" -- you get the idea.

Can't promise when I'll get this all done, but it will happen.

**Comment by barajus** [comment]
Sounds good! Thanks!

**Comment by ipspace** [comment]
I think I found a scalable solution (have to code it, but at least I have an idea what to do) and I plan to include it in netlab 1.8.0. The labs that have validation now will keep working as-is, as I'll add validation to other labs, they'll require the new software release for validation to work.

Will leave this issue open and close it once at least some other labs have validation.

**Comment by barajus** [comment]
Sounds very good :)

**Comment by ipspace** [comment]
Numerous validations added in #10. Some of the rest are hard to do, or would require very specific tests that are applicable only to a single lab exercise (example: BGP timers). Anyway, will keep this in mind and keep adding validations to new labs (now that I have the framework, it shouldn't be too hard).

**Comment by barajus** [comment]
This is awesome, good work 👍
